<a href="https://colab.research.google.com/github/nafisenik/DataMining_LSH_HW3/blob/main/LSH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Name: Nafiseh Nikeghbal
#### Student number: 400211438

In [1]:
import numpy as np
from numpy import dot

In [2]:
def create_fake_data(N, d):
    # returns X array with shape (N, d)
    vectors = [100 * np.random.rand(d) for i in range(0,N)]
    return vectors

def cosine_distance(x, y):
  # returns cosine distance between x and y
  distance = (x.dot(y.T)) / ((np.linalg.norm(x)) * (np.linalg.norm(y)))
  return distance

def find_k_nearest_neighbours(X, q, k):
  # returns indexes of the k-nearest-neighbours of vector q
  sorted_list = sorted(X, key = lambda s : cosine_distance(q,s))
  k_nearest = sorted_list[:k]
  return k_nearest

In [97]:
class Image:
    def __init__(self, f, d):
        # initiates f random vectors with dimension = d
        hp = [np.random.uniform(low = -1, size = d) for i in range(0,f)]
        self.hyperplanes = [h/(np.linalg.norm(h)) for h in hp]
        
    def hash_point(self, x):
        # returns list of numbers in {0, 1}
        reduced_dim =[]
        for hp in self.hyperplanes:
          if np.dot(x, hp) >= 0:
            reduced_dim.append(1)
          else:
            reduced_dim.append(0)
        return reduced_dim 

In [99]:
image = Image(5,20)


[1, 0, 1, 1, 0]

In [103]:
x = np.asarray(create_fake_data(1,20))
image.hash_point(x)

[0, 0, 1, 1, 0]

In [90]:
d = 10
f = 4
hp = [np.random.uniform(low = -1.0, size = d) for i in range(0,f)]
hyperplanes = [h/np.linalg.norm(h) for h in hp]

In [91]:
hp

[array([ 0.32255279, -0.23011105,  0.45196586, -0.13256728,  0.81605706,
        -0.29563709, -0.45735595, -0.6128109 ,  0.74392072, -0.55559284]),
 array([ 0.73315869, -0.97429421, -0.08644523,  0.11103621,  0.66518885,
         0.40806781,  0.49482989, -0.1041927 , -0.13273077, -0.78186424]),
 array([ 0.80303206,  0.74678727,  0.80602203, -0.51933447,  0.77164881,
         0.89815322,  0.58113038,  0.57799276,  0.27721385,  0.39340246]),
 array([ 0.27361058,  0.82579182, -0.6971069 ,  0.64744576, -0.04741802,
        -0.7783583 , -0.59401065,  0.93841098,  0.4080819 ,  0.00439084])]

In [92]:
hyperplanes

[array([ 0.20085144, -0.1432886 ,  0.28143608, -0.08254875,  0.50815321,
        -0.18409122, -0.28479246, -0.38159321,  0.4632344 , -0.3459639 ]),
 array([ 0.42327455, -0.56248933, -0.04990743,  0.06410454,  0.38403351,
         0.23558981,  0.28568016, -0.06015358, -0.07662946, -0.45139372]),
 array([ 0.38164174,  0.35491135,  0.38306272, -0.24681419,  0.36672682,
         0.42684816,  0.27618276,  0.2746916 ,  0.13174614,  0.18696489]),
 array([ 0.14282273,  0.4310573 , -0.36388471,  0.33796196, -0.02475186,
        -0.40629735, -0.31006922,  0.48984368,  0.21301577,  0.00229198])]

In [3]:
def create_fake_data2(N, d):
    # returns X array with shape (N, d)
    return 100 * np.random.rand(N, d)
    

def cosine_distance2(x, y):
    # returns cosine distance between x and y
    x_norm = np.linalg.norm(x)
    y_norm = np.linalg.norm(y)
    
    similiarity = np.dot(x, y.T)/(x_norm * y_norm) 
    distance = 1 - similiarity
    return similiarity
    

def find_k_nearest_neighbours2(X, q, k):
    # returns k-nearest-neighbours of vector q (least distance with vector q)
    #X_splitted = np.array_split(X, X.shape[0])
    return sorted(X, key = lambda v: cosine_distance(v, q))[:k]

In [93]:
class Signer:
    def __init__(self, f, d):
        # initiates f random vectors with dimension = d
        self.hyper_planes = []
        for i in range(0,f):
            h = np.random.uniform(low = -1.0, size = d)
            self.hyper_planes.append(h / np.linalg.norm(h))
        
    def hash_point(self, x):
        # returns list of numbers in {0, 1} -> right and left can be determined by inner product
        return [1 if np.dot(x, h) >= 0 else 0 for h in self.hyper_planes]

[ 0.58047641  0.77495268 -0.93544656  0.12918042 -0.92368316 -0.28792689
  0.95949347 -0.95191485  0.10257538  0.48879237]
[-0.19696097 -0.60946395 -0.09357755  0.55103942  0.85921588  0.04073384
  0.0313697  -0.28320601 -0.06304191 -0.22980242]
[-0.6718264  -0.00381772 -0.99489706  0.21611391  0.41015887  0.27288004
  0.18937408 -0.55548341  0.61893344 -0.8275331 ]
[ 0.77989413 -0.40005999 -0.50725895 -0.38854183  0.07096428 -0.55348306
  0.2618126  -0.329945    0.83733111 -0.96969873]


In [81]:
hyper_planes

[array([ 0.37424393, -0.39526762, -0.36490895,  0.12117267,  0.45233398,
         0.12718506, -0.02175866, -0.34670943, -0.46040429, -0.04928072]),
 array([-0.12343729, -0.3916094 , -0.55027161,  0.12391379,  0.01174208,
         0.0602637 , -0.21864962, -0.16212958,  0.01507168,  0.65966767]),
 array([-0.12997006, -0.17830744, -0.33181582, -0.25194506, -0.51946894,
         0.1752043 , -0.44900256,  0.15508384, -0.08044124, -0.49504199]),
 array([ 0.09016172,  0.00598122, -0.04306578,  0.37919195,  0.08215675,
        -0.1926357 , -0.3699318 ,  0.36535497,  0.51234779,  0.51913543])]

In [45]:
s = Signer(4,10)

h = np.random.uniform(low = -1.0, size = 4)
x = h / np.linalg.norm(h)
print(h)
print(x)

[-0.36104792 -0.53966336 -0.58690208 -0.37473714]
[-0.37921643 -0.56682009 -0.61643593 -0.39359451]


In [67]:
a = create_fake_data2(1,10)


In [61]:
s.hash_point(a)

[0, 0, 1, 0]

In [50]:
class Signer2:
    def __init__(self, f, d):
        # initiates f random vectors with dimension = d
        self.hyper_planes = []
        for i in range(0,f):
            h = np.random.uniform(low = -2, size = d)
            self.hyper_planes.append(h / np.linalg.norm(h))
        
    def hash_point(self, x):
        # returns list of numbers in {0, 1} -> right and left can be determined by inner product
        return [1 if np.dot(x, h) >= 0 else 0 for h in self.hyper_planes]

In [62]:
s2 = Signer2(4,10)


In [69]:
s2.hash_point(a)

[0, 0, 0, 0]